# Generated by Django 4.1.1 on 2022-09-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp_tasks', '0001_initial'),
        ('todoapp_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(to='todoapp_tasks.todotask'),
        ),
    ]
