# Generated by Django 4.1.1 on 2022-09-08 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 13, 14, 55, 180215)),
        ),
        migrations.AddField(
            model_name='todotask',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
