# Generated by Django 4.1.1 on 2022-09-08 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp_tasks', '0002_todotask_created_date_todotask_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 13, 15, 29, 735164, tzinfo=datetime.timezone.utc)),
        ),
    ]
